config/routes.rb
Rails.application.routes.draw do
  resources :transactions

  resources :lineitems

  resources :lines

  get 'pages/home'

  root 'pages#home'

end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base

	has_many :transactions

	validates_numericality_of :starting_amount

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base

	belongs_to :lineitem

	validates_numericality_of :trans_amount

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/lineitems_controller.rb
class LineitemsController < ApplicationController
  before_action :set_lineitem, only: [:show, :edit, :update, :destroy]




  # GET /lineitems
  # GET /lineitems.json
  def index
    @lineitems = Lineitem.all
  end

  # GET /lineitems/1
  # GET /lineitems/1.json
  def show
  end

  # GET /lineitems/new
  def new
    @lineitem = Lineitem.new
  end

  # GET /lineitems/1/edit
  def edit
  end

  # POST /lineitems
  # POST /lineitems.json
  def create
    @lineitem = Lineitem.new(lineitem_params)

    respond_to do |format|
      if @lineitem.save
        format.html { redirect_to root_path, notice: 'Lineitem was successfully created.' }
        format.json { render :show, status: :created, location: @lineitem }
      else
        format.html { render :new }
        format.json { render json: @lineitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lineitems/1
  # PATCH/PUT /lineitems/1.json
  def update
    respond_to do |format|
      if @lineitem.update(lineitem_params)
        format.html { redirect_to @lineitem, notice: 'Lineitem was successfully updated.' }
        format.json { render :show, status: :ok, location: @lineitem }
      else
        format.html { render :edit }
        format.json { render json: @lineitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lineitems/1
  # DELETE /lineitems/1.json
  def destroy
    @lineitem.destroy
    respond_to do |format|
      format.html { redirect_to lineitems_url, notice: 'Lineitem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lineitem
      @lineitem = Lineitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lineitem_params
      params.require(:lineitem).permit(:name, :starting_amount)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	helper BudgetTotal

  def home
  	@lineitems = Lineitem.all
  	@new_line = Lineitem.new
  	@transactions = Transaction.all
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    if params[:debit]
      @transaction.trans_amount = @transaction.trans_amount * -1
      @transaction.save
      redirect_to root_path
    elsif params[:credit]
      @transaction.save
      redirect_to root_path
    end

    #respond_to do |format|
    #  if @transaction.save
    #    format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
    #    format.json { render :show, status: :created, location: @transaction }
    #  else
    #    format.html { render :new }
    #    format.json { render json: @transaction.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:description, :trans_amount, :lineitem_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/budget_total.rb
module BudgetTotal

	def budget_total
		Lineitem.all.sum(:starting_amount)
	end

end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/remaining.rb
module Remaining

	def remaining_budget

	end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CTSample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lineitems/_form.html.erb
<%= form_for(@lineitem) do |f| %>
  <% if @lineitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lineitem.errors.count, "error") %> prohibited this lineitem from being saved:</h2>

      <ul>
      <% @lineitem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :starting_amount %><br>
    <%= f.text_field :starting_amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lineitems/edit.html.erb
<h1>Editing lineitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @lineitem %> |
<%= link_to 'Back', lineitems_path %>

app/views/lineitems/index.html.erb
<h1>Listing lineitems</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Starting amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lineitems.each do |lineitem| %>
      <tr>
        <td><%= lineitem.name %></td>
        <td><%= lineitem.starting_amount %></td>
        <td><%= link_to 'Show', lineitem %></td>
        <td><%= link_to 'Edit', edit_lineitem_path(lineitem) %></td>
        <td><%= link_to 'Destroy', lineitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lineitem', new_lineitem_path %>

app/views/lineitems/new.html.erb
<h1>New lineitem</h1>

<%= render 'form' %>

<%= link_to 'Back', lineitems_path %>

app/views/lineitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lineitem.name %>
</p>

<p>
  <strong>Starting amount:</strong>
  <%= @lineitem.starting_amount %>
</p>

<%= link_to 'Edit', edit_lineitem_path(@lineitem) %> |
<%= link_to 'Back', lineitems_path %>

app/views/pages/home.html.erb
<header>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="text-center">My Budget</h1>
			</div>
		</div>
	</div>
</header>

<main class="main-container">
	<div class="container">
		<div class="row">
			<div class="col-md-offset-2 col-md-8">
				<% if @lineitems.blank? %>
					<h3 class="text-center">You have not created any line items.</h3>

					<h3 class="text-center button"><a href="#" data-toggle="modal" data-target="#LIModal" class="big-button">Get Started</a></h3>
				<% else %>

				
				<h4><a href="#" data-toggle="modal" data-target="#LIModal">Add Line Item</a><span class="pull-right"><a href="#" data-toggle="modal" data-target="#transModal">Add Transaction</a><span></h4>
				<% end %>
				<% for lines in @lineitems %>
				<div class="panel panel-default">
					<div class="panel-heading">
						<div class="row">
							<div class="col-md-12">
								<h3 class="panel-title"><%= lines.name %></h2>
							</div>
							
						</div>
						
					</div>

					<div class="panel-body">
						<div class="row">
							<div class="col-md-6">
								<p>Starting Amount: <%= number_to_currency lines.starting_amount %></p>
							</div>
							<div class="col-md-6">
								<% if lines.starting_amount + lines.transactions.sum(:trans_amount) < 0 %>
								<p class="text-right"><span class="red">Remaining: <%= number_to_currency lines.starting_amount + lines.transactions.sum(:trans_amount) %></span></p>
									<% else %>
										<p class="text-right"><span class="green">Remaining: <%= number_to_currency lines.starting_amount + lines.transactions.sum(:trans_amount) %></span></p>
									<% end %>
								</p>

							</div>
						</div>
						<a href="" id="view">View Transactions</a>
						<a href="" id="hide">Hide Transactions</a>
						<div id="trans-list">
							<% for transaction in @transactions %>
							<div class="row">
								<div class="col-md-6">
									<p><%= transaction.description %></p>
								</div>
								<div class="col-md-6">
									<p class="text-right"><%= transaction.trans_amount %></p>
								</div>
							</div>
							<% end %>
						</div>
					</div>
				</div>
				<% end %>
				
			</div>
		</div>
	</div>
</main>
<% if @lineitems.present? %>
<footer>
	<div class="container">
		<div class="row">
			<div class="col-md-offset-2 col-md-8">
				<div class="row">
					<div class="col-md-6">
						<h3>Budget Total: <%= number_to_currency budget_total %></h3>
					</div>
					<div class="col-md-6">
						<h3 class="text-right">Total Remaining: <%= number_to_currency budget_total + Transaction.all.sum(:trans_amount) %></h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>
<% end %>

<div class="modal fade" id="LIModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <% if @lineitems.count < 1 %>
        <h4 class="modal-title text-center">Add your first line item!</h4>
        <% else %>
        <h4 class="modal-title text-center">Add another line item!</h4>
        <% end %>
      </div>
      <div class="modal-body">
        <%= form_for @new_line do |f| %>
        	<div class="form-group">
        		<label class="sr-only">Name</label>
        		<%= f.text_field :name, placeholder: "Name", class: "form-control" %>
        	</div>
        	<div class="form-group">
        		<label class="sr-only">Starting Amount</label>
        		<%= f.text_field :starting_amount, placeholder: "Starting Amount", class: "form-control" %>
        	</div>
        	<%= submit_tag "Add Line Item", class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="transModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        
        <h4 class="modal-title text-center">Add Transaction</h4>
        
      </div>
      <div class="modal-body">
        <%= form_for Transaction.new do |f| %>
        	<div class="form-group">
        		<label class="sr-only">Description</label>
        		<%= f.text_field :description, placeholder: "Description", class: "form-control" %>
        	</div>
        	<div class="form-group">
        		<label class="sr-only">Starting Amount</label>
        		<%= f.text_field :trans_amount, placeholder: "Transaction Amount", class: "form-control" %>
        	</div>
        	<div class="form-group">
        		<%= f.collection_select :lineitem_id, Lineitem.all, :id, :name, {prompt: "--apply to line item--"}, {class: "form-control"} %>
        		<!--<select class="form-control">
        			<option val="">-- select line item --</option>
  						<option>2</option>
  						<option>3</option>
  						<option>4</option>
  						<option>5</option>
        		</select>-->
        	</div>
        	<%= submit_tag "Add as Debit", name: "debit", class: "btn btn-danger" %>
        	<%= submit_tag "Add as Credit", name: "credit", class: "btn btn-success" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :trans_amount %><br>
    <%= f.text_field :trans_amount %>
  </div>
  <div class="field">
    <%= f.label :lineitem_id %><br>
    <%= f.number_field :lineitem_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Trans amount</th>
      <th>Lineitem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.description %></td>
        <td><%= transaction.trans_amount %></td>
        <td><%= transaction.lineitem_id %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<p>
  <strong>Trans amount:</strong>
  <%= @transaction.trans_amount %>
</p>

<p>
  <strong>Lineitem:</strong>
  <%= @transaction.lineitem_id %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>